tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "neovim"
brew "node"
brew "rust-analyzer"
brew "watchman"

cask "1password"
cask "ableton-live-suite"
cask "alfred"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "native-access"
cask "obs"
cask "postman"
cask "splice"
cask "visual-studio-code"
cask "zoom"
