tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "cocoapods"
brew "git"
brew "golang"

brew "ghc"
brew "mas"
brew "neovim"
brew "openssl"
brew "pipx"
brew "pyenv"
brew "readline"
brew "rust-analyzer"
brew "sqlite3"
brew "starship"
brew "watchman"
brew "xz"
brew "zlib"

cask "1password"
cask "alfred"
cask "docker"
cask "dropbox"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "splice"
cask "visual-studio-code"
cask "zoom"

mas "iA Writer", id: 775737590
